### PR TITLE
Opdater kalender + tilføj Prosas arrangement

### PR DESCRIPTION
**Pull request by benjaoming**
Looks good?

### CODE REVIEW

**Comment by valberg** [comment]
@benjaoming: Cryptohagen.dk is for Cryptohagen events only. We should create the Information/PROSA event on cryptoparty.dk ;)

**Comment by benjaoming** [comment]
What's wrong with advertising other people's related events in Copenhagen?

**Comment by benjaoming** [comment]
Well meh, just removed it.

**Comment by benjaoming** [comment]
ping @valberg

**Pull request merged**
